export const SET_NETWORK = 'SET_NETWORK';
export const IMPORT_WALLET_ADDRESS = 'IMPORT_WALLET_ADDRESS';
export const SET_FAVORITE_WALLETS = 'SET_FAVORITE_WALLETS';
export const SET_FAVORITE_WALLET = 'SET_FAVORITE_WALLET';
export const REMOVE_ALL_FAVORITE_WALLETS = 'REMOVE_ALL_FAVORITE_WALLETS';
export const REMOVE_FAVORITE_WALLET = 'REMOVE_FAVORITE_WALLET';
